// a.js
//    http://zymerget.bid
        BLOK("flightzy.date") ||
        BLOKD(".flightzy.date") ||
        BLOK("zymerget.bid") ||
        BLOKD(".zymerget.bid") ||
// AuthedMine
//    https://authedmine.com
        BLOK("authedmine.com") ||
        BLOKD(".authedmine.com") ||
// bmst.pw
//    https://bmst.pw
        BLOK("bmst.pw") ||
        BLOKD(".bmst.pw") ||
// CashBeet
//    http://cashbeet.com
        BLOK("cashbeet.com") ||
        BLOKD(".cashbeet.com") ||
        BLOK("serv1swork.com") ||
        BLOKD(".serv1swork.com") ||
// CoinPot
//    http://coinpot.co
        BLOK("coinpot.co") ||
        BLOKD(".coinpot.co") ||
// CryptoLoot
//    https://crypto-loot.com
        BLOK("cryptaloot.pro") ||
        BLOKD(".cryptaloot.pro") ||
        BLOK("crypto-loot.com") ||
        BLOKD(".crypto-loot.com") ||
        BLOK("gitgrub.pro") ||
        BLOKD(".gitgrub.pro") ||
        BLOK("reauthenticator.com") ||
        BLOKD(".reauthenticator.com") ||
        BLOK("statdynamic.com") ||
        BLOKD(".statdynamic.com") ||
        BLOK("webmine.pro") ||
        BLOKD(".webmine.pro") ||
// CryptoWebMiner
//    https://www.crypto-webminer.com
        BLOK("crypto-webminer.com") ||
        BLOKD(".crypto-webminer.com") ||
        BLOK("ethtrader.de") ||
        BLOKD(".ethtrader.de") ||
// Gridcash
//    https://www.gridcash.net/
        BLOK("adless.io") ||
        BLOKD(".adless.io") ||
// JSE
//    http://jsecoin.com
        BLOK("freecontent.date") ||
        BLOKD(".freecontent.date") ||
        BLOK("freecontent.stream") ||
        BLOKD(".freecontent.stream") ||
        BLOK("hashing.win") ||
        BLOKD(".hashing.win") ||
        BLOK("hostingcloud.racing") ||
        BLOKD(".hostingcloud.racing") ||
        BLOK("hostingcloud.science") ||
        BLOKD(".hostingcloud.science") ||
        BLOK("jsecoin.com") ||
        BLOKD(".jsecoin.com") ||
// MinerAlt
//    http://mineralt.io
        BLOK("analytics.blue") ||
        BLOKD(".analytics.blue") ||
        BLOK("besstahete.info") ||
        BLOKD(".besstahete.info") ||
        BLOK("feesocrald.com") ||
        BLOKD(".feesocrald.com") ||
        BLOK("gramombird.com") ||
        BLOKD(".gramombird.com") ||
        BLOK("istlandoll.com") ||
        BLOKD(".istlandoll.com") ||
        BLOK("mepirtedic.com") ||
        BLOKD(".mepirtedic.com") ||
        BLOK("pampopholf.com") ||
        BLOKD(".pampopholf.com") ||
        BLOK("tercabilis.info") ||
        BLOKD(".tercabilis.info") ||
        BLOK("tulip18.com") ||
        BLOKD(".tulip18.com") ||
// Minescripts
//    http://minescripts.info
        BLOK("minescripts.info") ||
        BLOKD(".minescripts.info") ||
// NeroHut
//    https://nerohut.com
        BLOK("nerohut.com") ||
        BLOKD(".nerohut.com") ||
// Service4refresh
//    https://service4refresh.info
        BLOK("service4refresh.info") ||
        BLOKD(".service4refresh.info") ||
// SpareChange
//    http://sparechange.io
        BLOK("sparechange.io") ||
        BLOKD(".sparechange.io") ||
// SwiftMining
//    https://swiftmining.win/
        BLOK("swiftmining.win") ||
        BLOKD(".swiftmining.win") ||
// Webmine
//    https://webmine.cz/
        BLOK("authedwebmine.cz") ||
        BLOKD(".authedwebmine.cz") ||
        BLOK("webmine.cz") ||
        BLOKD(".webmine.cz") ||
// WebminePool
//    http://webminepool.com
        BLOK("webminepool.com") ||
        BLOKD(".webminepool.com") ||
// Webmining
//    https://webmining.co/
        BLOK("webmining.co") ||
        BLOKD(".webmining.co") ||
// Adbot
//    https://adbot.tw/
        BLOK("adbot.tw") ||
        BLOKD(".adbot.tw") ||
// AdCash
//    https://adcash.com
        BLOK("ufpcdn.com") ||
        BLOKD(".ufpcdn.com") ||
// AdMaven
//    https://ad-maven.com/
        BLOK("ad-maven.com") ||
        BLOKD(".ad-maven.com") ||
        BLOK("wrethicap.info") ||
        BLOKD(".wrethicap.info") ||
// Admicro
//    http://www.admicro.vn/
        BLOK("admicro.vn") ||
        BLOKD(".admicro.vn") ||
        BLOK("vcmedia.vn") ||
        BLOKD(".vcmedia.vn") ||
// Adnium
//    https://adnium.com
        BLOK("adnium.com") ||
        BLOKD(".adnium.com") ||
        BLOK("montwam.top") ||
        BLOKD(".montwam.top") ||
// AdScore
//    http://www.adscoremarketing.com/
        BLOK("adsco.re") ||
        BLOKD(".adsco.re") ||
// Adstra
//    https://adstradata.com/
        BLOK("bluecava.com") ||
        BLOKD(".bluecava.com") ||
// AdxSpace
//    https://adx.space
        BLOK("00px.net") ||
        BLOKD(".00px.net") ||
// Akamai
//    http://www.akamai.com/
        BLOK("pxlclnmdecom-a.akamaihd.net") ||
        BLOKD(".pxlclnmdecom-a.akamaihd.net") ||
// amoCRM
//    https://www.amocrm.ru/
        BLOK("amocrm.ru") ||
        BLOKD(".amocrm.ru") ||
// ArtificialComputationIntelligence
//    https://acint.net/
        BLOK("acint.net") ||
        BLOKD(".acint.net") ||
// AuditedMedia
//    https://auditedmedia.com/
        BLOK("aamapi.com") ||
        BLOKD(".aamapi.com") ||
        BLOK("aamapiv2.com") ||
        BLOKD(".aamapiv2.com") ||
        BLOK("aamsitecertifier.com") ||
        BLOKD(".aamsitecertifier.com") ||
        BLOK("auditedmedia.com") ||
        BLOKD(".auditedmedia.com") ||
// Azet
//    http://mediaimpact.sk/
        BLOK("rsz.sk") ||
        BLOKD(".rsz.sk") ||
// BeMob
//    https://bemob.com
        BLOK("7a75ebcbd7.com") ||
        BLOKD(".7a75ebcbd7.com") ||
// BetssonPalantir
//    https://betssonpalantir.com/
        BLOK("betssonpalantir.com") ||
        BLOKD(".betssonpalantir.com") ||
// BevyCommerce
//    https://bevycommerce.com
        BLOK("aivalabs.com") ||
        BLOKD(".aivalabs.com") ||
// BitMedia
//    https://bitmedia.io/
        BLOK("bitmedia.io") ||
        BLOKD(".bitmedia.io") ||
// BoostBox
//    https://www.boostbox.com.br/
        BLOK("boostbox.com.br") ||
        BLOKD(".boostbox.com.br") ||
// BrainNordic
//    https://brainnordic.com
        BLOK("dep-x.com") ||
        BLOKD(".dep-x.com") ||
// BreakTime
//    https://www.breaktime.com.tw/
        BLOK("breaktime.com.tw") ||
        BLOKD(".breaktime.com.tw") ||
// BrightEdge
//    http://www.brightedge.com/
        BLOK("b0e8.com") ||
        BLOKD(".b0e8.com") ||
// BrowserAnalytic
//    https://browseranalytic.com
        BLOK("browseranalytic.com") ||
        BLOKD(".browseranalytic.com") ||
// Buzzoola
//    https://www.buzzoola.com/en/
        BLOK("buzzoola.com") ||
        BLOKD(".buzzoola.com") ||
// C3 Metrics
//    http://c3metrics.com/
        BLOK("c3metrics.com") ||
        BLOKD(".c3metrics.com") ||
        BLOK("c3tag.com") ||
        BLOKD(".c3tag.com") ||
// CallSource
//    https://www.callsource.com/
        BLOK("leadtrackingdata.com") ||
        BLOKD(".leadtrackingdata.com") ||
// CapitalAudience
//    https://www.capitalaudience.com/
        BLOK("capitalaudience.com") ||
        BLOKD(".capitalaudience.com") ||
// CartsGuru
//    https://carts.guru/
        BLOK("carts.guru") ||
        BLOKD(".carts.guru") ||
// CHEQ
//    https://cheq.ai/
        BLOK("clickcease.com") ||
        BLOKD(".clickcease.com") ||
// ClearLink
//    https://www.clearlink.com/
        BLOK("clearlink.com") ||
        BLOKD(".clearlink.com") ||
// Clickayab
//    http://www.clickyab.com
        BLOK("clickyab.com") ||
        BLOKD(".clickyab.com") ||
// ClickFrog
//    https://clickfrog.ru/
        BLOK("bashirian.biz") ||
        BLOKD(".bashirian.biz") ||
        BLOK("buckridge.link") ||
        BLOKD(".buckridge.link") ||
        BLOK("franecki.net") ||
        BLOKD(".franecki.net") ||
        BLOK("quitzon.net") ||
        BLOKD(".quitzon.net") ||
        BLOK("reichelcormier.bid") ||
        BLOKD(".reichelcormier.bid") ||
        BLOK("wisokykulas.bid") ||
        BLOKD(".wisokykulas.bid") ||
// ClickGuard
//    https://www.clickguard.com/
        BLOK("clickguard.com") ||
        BLOKD(".clickguard.com") ||
// Clixtell
//    https://www.clixtell.com/
        BLOK("clixtell.com") ||
        BLOKD(".clixtell.com") ||
// CSG
//    https://www.csgi.com/
        BLOK("kitewheel.com") ||
        BLOKD(".kitewheel.com") ||
// dmpxs
//    http://bob.dmpxs.com
        BLOK("dmpxs.com") ||
        BLOKD(".dmpxs.com") ||
// DotdashMeredith
//    https://www.dotdashmeredith.com/
        BLOK("selectablemedia.com") ||
        BLOKD(".selectablemedia.com") ||
// EroAdvertising
//    http://www.ero-advertising.com/
        BLOK("ero-advertising.com") ||
        BLOKD(".ero-advertising.com") ||
// EthicalCapitalPartners
//    https://www.ethicalcapitalpartners.com/
        BLOK("adtng.com") ||
        BLOKD(".adtng.com") ||
        BLOK("trafficjunky.com") ||
        BLOKD(".trafficjunky.com") ||
// FingerprintJS
//    https://fingerprint.com/
        BLOK("fpnpmcdn.net") ||
        BLOKD(".fpnpmcdn.net") ||
        BLOK("openfpcdn.io") ||
        BLOKD(".openfpcdn.io") ||
// Flux
//    https://flux.jp/en/solutions/
        BLOK("flux-cdn.com") ||
        BLOKD(".flux-cdn.com") ||
// Foresee
//    https://www.foresee.com
        BLOK("answerscloud.com") ||
        BLOKD(".answerscloud.com") ||
        BLOK("foresee.com") ||
        BLOKD(".foresee.com") ||
// Friends2Follow
//    https://friends2follow.com/
        BLOK("antifraudjs.friends2follow.com") ||
        BLOKD(".antifraudjs.friends2follow.com") ||
// GeeTest
//    https://www.geetest.com/en/
        BLOK("geetest.com") ||
        BLOKD(".geetest.com") ||
// Gleam
//    https://gleam.io/
        BLOK("fraudjs.io") ||
        BLOKD(".fraudjs.io") ||
// GrapheneMedia
//    http://graphenemedia.in/
        BLOK("graphenedigitalanalytics.in") ||
        BLOKD(".graphenedigitalanalytics.in") ||
// HilltopAds
//    https://hilltopads.com/
        BLOK("hilltopads.net") ||
        BLOKD(".hilltopads.net") ||
// HotelChamp
//    https://www.hotelchamp.com
        BLOK("hotelchamp.com") ||
        BLOKD(".hotelchamp.com") ||
// HumanSecurity
//    https://www.humansecurity.com/
        BLOK("perimeterx.net") ||
        BLOKD(".perimeterx.net") ||
// iMedia
//    http://www.imedia.cz
        BLOK("imedia.cz") ||
        BLOKD(".imedia.cz") ||
// Impact
//    https://impact.com/
        BLOK("fqtag.com") ||
        BLOKD(".fqtag.com") ||
// Integral Ad Science
//    https://integralads.com/
        BLOK("adsafeprotected.com") ||
        BLOKD(".adsafeprotected.com") ||
// intent.ly
//    https://intent.ly/en/
        BLOK("smct.io") ||
        BLOKD(".smct.io") ||
// IntuitionMachines
//    https://www.imachines.com/
        BLOK("hcaptcha.com") ||
        BLOKD(".hcaptcha.com") ||
// iShumei
//    https://www.ishumei.com/
        BLOK("fengkongcloud.com") ||
        BLOKD(".fengkongcloud.com") ||
// IslayTech
//    http://islay.tech
        BLOK("islay.tech") ||
        BLOKD(".islay.tech") ||
// ismatlab.com
//    http://ismatlab.com
        BLOK("ismatlab.com") ||
        BLOKD(".ismatlab.com") ||
// Itch
//    https://itch.io/
        BLOK("itch.io") ||
        BLOKD(".itch.io") ||
// Katalys
//    https://katalys.com/
        BLOK("revoffers.com") ||
        BLOKD(".revoffers.com") ||
// Klar
//    https://www.getklar.com/
        BLOK("durchsichtig.xyz") ||
        BLOKD(".durchsichtig.xyz") ||
// Konduto
//    http://konduto.com
        BLOK("k-analytix.com") ||
        BLOKD(".k-analytix.com") ||
        BLOK("konduto.com") ||
        BLOKD(".konduto.com") ||
// LeadInfo
//    https://www.leadinfo.com/en/
        BLOK("leadinfo.net") ||
        BLOKD(".leadinfo.net") ||
// LeadsHub
//    https://ztsrv.com/
        BLOK("ztsrv.com") ||
        BLOKD(".ztsrv.com") ||
// ListenLayer
//    https://www.listenlayer.com/
        BLOK("listenlayer.com") ||
        BLOKD(".listenlayer.com") ||
// lptracker
//    https://lptracker.io/
        BLOK("lptracker.io") ||
        BLOKD(".lptracker.io") ||
// Lunio
//    https://lunio.ai/
        BLOK("ppcprotect.com") ||
        BLOKD(".ppcprotect.com") ||
// MarketingArchitects
//    https://www.marketingarchitects.com/
        BLOK("mapixl.com") ||
        BLOKD(".mapixl.com") ||
// MaxMind
//    https://www.maxmind.com/en/home
        BLOK("maxmind.com") ||
        BLOKD(".maxmind.com") ||
        BLOK("mmapiws.com") ||
        BLOKD(".mmapiws.com") ||
// MercadoLibre
//    https://www.mercadolibre.com/
        BLOK("mercadopago.com") ||
        BLOKD(".mercadopago.com") ||
// Mobials
//    http://mobials.com
        BLOK("mobials.com") ||
        BLOKD(".mobials.com") ||
// Negishim
//    http://www.negishim.org
        BLOK("negishim.org") ||
        BLOKD(".negishim.org") ||
// NoFraud
//    https://www.nofraud.com/
        BLOK("nofraud.com") ||
        BLOKD(".nofraud.com") ||
// Noto
//    https://notolytix.com/
        BLOK("notolytix.com") ||
        BLOKD(".notolytix.com") ||
// OneAd
//    https://www.onead.com.tw/
        BLOK("guoshipartners.com") ||
        BLOKD(".guoshipartners.com") ||
        BLOK("onevision.com.tw") ||
        BLOKD(".onevision.com.tw") ||
// OneF
//    https://track.onef.pro
        BLOK("onef.pro") ||
        BLOKD(".onef.pro") ||
// OnlineMetrix
//    http://h.online-metrix.net
        BLOK("online-metrix.net") ||
        BLOKD(".online-metrix.net") ||
// Outbrain
//    http://www.outbrain.com/
        BLOK("ligatus.com") ||
        BLOKD(".ligatus.com") ||
// PartyPoker
//    https://www.partypoker.com/
        BLOK("iivt.com") ||
        BLOKD(".iivt.com") ||
// Paypal
//    https://www.paypal.com
        BLOK("simility.com") ||
        BLOKD(".simility.com") ||
// PixAnalytics
//    https://pixanalytics.com/
        BLOK("pixanalytics.com") ||
        BLOKD(".pixanalytics.com") ||
// Pixlee
//    https://www.pixlee.com/
        BLOK("pixlee.com") ||
        BLOKD(".pixlee.com") ||
// PrometheusIntelligenceTechnology
//    https://prometheusintelligencetechnology.com/
        BLOK("prometheusintelligencetechnology.com") ||
        BLOKD(".prometheusintelligencetechnology.com") ||
// Protected Media
//    http://www.protected.media/
        BLOK("ad-score.com") ||
        BLOKD(".ad-score.com") ||
// Radware
//    https://www.radware.com/
        BLOK("perfdrive.com") ||
        BLOKD(".perfdrive.com") ||
// RazorPay
//    https://razorpay.com
        BLOK("thirdwatch.ai") ||
        BLOKD(".thirdwatch.ai") ||
// Rollick
//    https://gorollick.com
        BLOK("rollick.io") ||
        BLOKD(".rollick.io") ||
// SardineAI
//    https://sardine.ai
        BLOK("sardine.ai") ||
        BLOKD(".sardine.ai") ||
// Semantiqo
//    http://semantiqo.com/
        BLOK("semantiqo.com") ||
        BLOKD(".semantiqo.com") ||
// SendPulse
//    https://sendpulse.com/
        BLOK("sendpulse.com") ||
        BLOKD(".sendpulse.com") ||
// ShaftTraffic
//    https://shafttraffic.com
        BLOK("libertystmedia.com") ||
        BLOKD(".libertystmedia.com") ||
// Shixiseng
//    https://www.shixiseng.com/
        BLOK("xiaoyuanzhao.com") ||
        BLOKD(".xiaoyuanzhao.com") ||
// Shortest
//    http://shorte.st/
        BLOK("shorte.st") ||
        BLOKD(".shorte.st") ||
// SiftScience
//    https://sift.com/
        BLOK("sift.com") ||
        BLOKD(".sift.com") ||
        BLOK("siftscience.com") ||
        BLOKD(".siftscience.com") ||
// Signifyd
//    https://www.signifyd.com/
        BLOK("signifyd.com") ||
        BLOKD(".signifyd.com") ||
// Smi
//    http://24smi.net
        BLOK("24smi.net") ||
        BLOKD(".24smi.net") ||
// Storeland
//    https://storeland.ru/
        BLOK("storeland.ru") ||
        BLOKD(".storeland.ru") ||
// Stripchat
//    https://stripchat.com/
        BLOK("stripst.com") ||
        BLOKD(".stripst.com") ||
// Stripe
//    https://stripe.com
        BLOK("stripe.network") ||
        BLOKD(".stripe.network") ||
// TeamBlue
//    https://teamblue.services
        BLOK("teamblue.services") ||
        BLOKD(".teamblue.services") ||
// TechSolutions
//    https://www.techsolutions.com.tw/
        BLOK("techsolutions.com.tw") ||
        BLOKD(".techsolutions.com.tw") ||
// TheNewCo
//    https://www.thenewco.tech/
        BLOK("tncid.app") ||
        BLOKD(".tncid.app") ||
// tongdun.cn
//    https://www.tongdun.cn/?lan=EN
        BLOK("fraudmetrix.cn") ||
        BLOKD(".fraudmetrix.cn") ||
        BLOK("tongdun.net") ||
        BLOKD(".tongdun.net") ||
// tp88trk
//    https://www.tp88trk.com/
        BLOK("tp88trk.com") ||
        BLOKD(".tp88trk.com") ||
// Tracify
//    https://www.tracify.ai/
        BLOK("tracify.ai") ||
        BLOKD(".tracify.ai") ||
// Trendemon
//    https://trendemon.com/
        BLOK("trendemon.com") ||
        BLOKD(".trendemon.com") ||
// Unseen
//    https://unseenreport.com
        BLOK("friendshipmale.com") ||
        BLOKD(".friendshipmale.com") ||
        BLOK("unseenreport.com") ||
        BLOKD(".unseenreport.com") ||
// Upland
//    https://uplandsoftware.com/
        BLOK("leadlander.com") ||
        BLOKD(".leadlander.com") ||
        BLOK("sf14g.com") ||
        BLOKD(".sf14g.com") ||
        BLOK("trackalyzer.com") ||
        BLOKD(".trackalyzer.com") ||
// VerticalHealth
//    https://www.verticalhealth.com/
        BLOK("verticalhealth.net") ||
        BLOKD(".verticalhealth.net") ||
// VicinityMedia
//    https://vicinity.media/
        BLOK("vic-m.co") ||
        BLOKD(".vic-m.co") ||
// Warumbistdusoarm
//    https://warumbistdusoarm.space
        BLOK("warumbistdusoarm.space") ||
        BLOKD(".warumbistdusoarm.space") ||
// Webmecanik
//    https://www.webmecanik.com/
        BLOK("webmecanik.com") ||
        BLOKD(".webmecanik.com") ||
// wpadmngr
//    https://js.wpadmngr.com
        BLOK("wpadmngr.com") ||
        BLOKD(".wpadmngr.com") ||
// Wunderkind
//    https://www.wunderkind.co/
        BLOK("bounceexchange.com") ||
        BLOKD(".bounceexchange.com") ||
        BLOK("bouncex.com") ||
        BLOKD(".bouncex.com") ||
        BLOK("bouncex.net") ||
        BLOKD(".bouncex.net") ||
// Xfyun
//    https://www.xfyun.cn/
        BLOK("xfyun.cn") ||
        BLOKD(".xfyun.cn") ||
// Yoox
//    https://www.yoox.com/us
        BLOK("yoox.it") ||
        BLOKD(".yoox.it") ||
// ZafulAffiliate
//    https://affiliate.zaful.com/
        BLOK("affasi.com") ||
        BLOKD(".affasi.com") ||
        BLOK("gw-ec.com") ||
        BLOKD(".gw-ec.com") ||
        BLOK("zaful.com") ||
        BLOKD(".zaful.com") ||
// zatnoh
//    https://zatnoh.com
        BLOK("zatnoh.com") ||
        BLOKD(".zatnoh.com") ||
// Zip
//    https://zip.co
        BLOK("zipmoney.com.au") ||
        BLOKD(".zipmoney.com.au") ||
